### PR TITLE
fixed separator characters to work with powerline fonts

### PR DESCRIPTION
**Pull request by MoOmEeN**
fix for issue reported [here] (https://github.com/erikw/tmux-powerline/issues/33#issuecomment-14959749)

### CODE REVIEW

**Comment by MoOmEeN** [comment]
fix for https://github.com/erikw/tmux-powerline/issues/190

**Comment by erikw** [comment]
Well it was never broken since tmux-powerline uses glyphs from the older versions of the powerline patched fonts. But I'm OK with bringing in this patch as I guess the new patched fonts are more common nowadays :)

**Comment by MoOmEeN** [comment]
Hi,
Yeah. I realised that it uses different font bit too late. But imho good
idea to switch to this font since vim-airline and oh-my-zsh themes use it
already.

Thanks
MoOmEeN


On Pn, lut 16, 2015 at 19:41 , Erik Westrup <notifications@github.com>
wrote:

Well it was never broken since tmux-powerline uses glyphs from the older
versions of the powerline patched fonts. But I'm OK with bringing in this
patch as I guess the new patched fonts are more common nowadays :)


—
Reply to this email directly or view it on GitHub
<https://github.com/erikw/tmux-powerline/pull/193#issuecomment-74554029>.










-- 
Sent from MetroMail

**Comment by MoOmEeN** [comment]
@erikw looks like you merged also my another commit. That wasn't my idea, that other one is just my fix for gmail count feature. Might be useful as well but probably as separate commit slightly modified (using grep instead of ggrep)

**Comment by erikw** [comment]
Yup I saw that, so I reverted that one directly afterwards :)

-- 
Erik Westrup
<erik.westrup@gmail.com>
(+46) 0738-286060 | 2r.se
Lagerbrings väg 8E, 22460 Lund, Sweden
-----------------------------------------
This email is encrypted with 2ROT-13.

**Pull request merged**
